services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Edge port
    env_file:
      - "./.env"
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh" # ready hook
      - "./volume:/var/lib/localstack"